version: "3.9"

services:
  auth_server:
    build: ./backend/auth_server
    container_name: auth_server
    env_file: 
      - ./backend/auth_server/.env
    environment:
      - APP_ENV=development
    volumes:
      - ./backend/auth_server:/app
    ports:
      - "5002:5002"

  workouts_server:
    build: ./backend/workout_server
    container_name: workouts_server
    env_file:
      - ./backend/workout_server/.env
    environment:
      - APP_ENV=development
    volumes:
      - ./backend/workout_server:/app
    ports:
      - "5001:5001"

  liftbot_server:
    build: ./backend/liftbot_server
    container_name: liftbot_server
    env_file:
      - ./backend/liftbot_server/.env
    environment:
      - APP_ENV=development
      - AUTH_SERVER_URL=http://auth_server:5002/api/accounts
      - WORKOUT_SERVER_URL=http://workouts_server:5001/api/workouts
    volumes:
      - ./backend/liftbot_server:/app
    ports:
      - "5003:5003"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: ["npm", "start"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
